export default {
    GET_OPEN_WEATHER_MAP_LOCATIONS_REQUEST: 'GET_OPEN_WEATHER_MAP_LOCATIONS_REQUEST',
    GET_OPEN_WEATHER_MAP_LOCATIONS_SUCCESS: 'GET_OPEN_WEATHER_MAP_LOCATIONS_SUCCESS',
    GET_OPEN_WEATHER_MAP_LOCATIONS_FAILURE: 'GET_OPEN_WEATHER_MAP_LOCATIONS_FAILURE',
    SET_MARKED_LOCATION: 'SET_MARKED_LOCATION',
    GET_OPEN_WEATHER_MAP_FORECASTS_LOCATIONS_REQUEST: 'GET_OPEN_WEATHER_MAP_FORECASTS_LOCATIONS_REQUEST',
    GET_OPEN_WEATHER_MAP_FORECASTS_LOCATIONS_SUCCESS: 'GET_OPEN_WEATHER_MAP_FORECASTS_LOCATIONS_SUCCESS',
    GET_OPEN_WEATHER_MAP_FORECASTS_LOCATIONS_FAILURE: 'GET_OPEN_WEATHER_MAP_FORECASTS_LOCATIONS_FAILURE',
}